title: Thomas Zhu's Blog

url: http://thomaszhu.cn

baseurl: ""

author: Thomas Zhu

social_links:
  email: thomas.zhu.sh@hotmail.com
  github: HanwenZhu
  twitter: hanwen_zhu
  youtube_channel: UCyxcgjrYx4tRJuA5srnZBOQ
  youtube_channel_name: Curiositas

share_links:
  twitter: true
  facebook: true

google_analytics: UA-148159096-1

disqus: thomaszhu

date_format: "%B %-d, %Y"

timezone: China/Shanghai

permalink: /:title/

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine:

plugins:
  - jekyll-katex

katex:
  js_path: ./assets/vendors/katex

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: false  # TODO, share function not ready yet
  -
    scope:
      path: ""
    values:
      layout: page

exclude:
  - .sass_cache/
  - .jekyll_cache/
  - .gitignore
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
  - README.md
